/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DotworkspaceUiPrototypeRouteImport } from './routes/[.]workspace-ui-prototype'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as DotslackSetupRouteImport } from './routes/[.]slack.setup'
import { Route as DotnotionSetupRouteImport } from './routes/[.]notion.setup'
import { Route as DotgithubSetupRouteImport } from './routes/[.]github.setup'
import { Route as DotauthSignInRouteImport } from './routes/[.]auth.sign-in'
import { Route as DotauthResetPasswordRouteImport } from './routes/[.]auth.reset-password'
import { Route as DotauthDeviceRouteImport } from './routes/[.]auth.device'
import { Route as DotauthConsentRouteImport } from './routes/[.]auth.consent'
import { Route as DotauthAccountRouteImport } from './routes/[.]auth.account'
import { Route as DotauthAuthViewRouteImport } from './routes/[.]auth.$authView'
import { Route as DotampEventsRouteImport } from './routes/[.]amp.events'
import { Route as OrgSlugSetupRouteImport } from './routes/$orgSlug.setup'
import { Route as OrgSlugConnectorsRouteImport } from './routes/$orgSlug.connectors'
import { Route as DotauthOrganizationOrganizationViewRouteImport } from './routes/[.]auth.organization.$organizationView'
import { Route as DotauthAccountAccountViewRouteImport } from './routes/[.]auth.account.$accountView'
import { Route as OrgSlugWsWorkspaceSlugRouteImport } from './routes/$orgSlug.ws.$workspaceSlug'
import { Route as OrgSlugWorkspacesNewRouteImport } from './routes/$orgSlug.workspaces.new'
import { Route as OrgSlugOrganizationOrganizationViewRouteImport } from './routes/$orgSlug.organization.$organizationView'
import { Route as OrgSlugWsWorkspaceSlugIndexRouteImport } from './routes/$orgSlug.ws.$workspaceSlug.index'
import { Route as OrgSlugWsWorkspaceSlugConversationIdRouteImport } from './routes/$orgSlug.ws.$workspaceSlug.$conversationId'
import { Route as OrgSlugRepositoriesGithubSetupRouteImport } from './routes/$orgSlug.repositories.github.setup'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DotworkspaceUiPrototypeRoute = DotworkspaceUiPrototypeRouteImport.update({
  id: '/.workspace-ui-prototype',
  path: '/.workspace-ui-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const DotslackSetupRoute = DotslackSetupRouteImport.update({
  id: '/.slack/setup',
  path: '/.slack/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DotnotionSetupRoute = DotnotionSetupRouteImport.update({
  id: '/.notion/setup',
  path: '/.notion/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DotgithubSetupRoute = DotgithubSetupRouteImport.update({
  id: '/.github/setup',
  path: '/.github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthSignInRoute = DotauthSignInRouteImport.update({
  id: '/.auth/sign-in',
  path: '/.auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthResetPasswordRoute = DotauthResetPasswordRouteImport.update({
  id: '/.auth/reset-password',
  path: '/.auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthDeviceRoute = DotauthDeviceRouteImport.update({
  id: '/.auth/device',
  path: '/.auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthConsentRoute = DotauthConsentRouteImport.update({
  id: '/.auth/consent',
  path: '/.auth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthAccountRoute = DotauthAccountRouteImport.update({
  id: '/.auth/account',
  path: '/.auth/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DotauthAuthViewRoute = DotauthAuthViewRouteImport.update({
  id: '/.auth/$authView',
  path: '/.auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const DotampEventsRoute = DotampEventsRouteImport.update({
  id: '/.amp/events',
  path: '/.amp/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSetupRoute = OrgSlugSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugConnectorsRoute = OrgSlugConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => OrgSlugRoute,
} as any)
const DotauthOrganizationOrganizationViewRoute =
  DotauthOrganizationOrganizationViewRouteImport.update({
    id: '/.auth/organization/$organizationView',
    path: '/.auth/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotauthAccountAccountViewRoute =
  DotauthAccountAccountViewRouteImport.update({
    id: '/$accountView',
    path: '/$accountView',
    getParentRoute: () => DotauthAccountRoute,
  } as any)
const OrgSlugWsWorkspaceSlugRoute = OrgSlugWsWorkspaceSlugRouteImport.update({
  id: '/ws/$workspaceSlug',
  path: '/ws/$workspaceSlug',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugWorkspacesNewRoute = OrgSlugWorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugOrganizationOrganizationViewRoute =
  OrgSlugOrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugWsWorkspaceSlugIndexRoute =
  OrgSlugWsWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugWsWorkspaceSlugRoute,
  } as any)
const OrgSlugWsWorkspaceSlugConversationIdRoute =
  OrgSlugWsWorkspaceSlugConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => OrgSlugWsWorkspaceSlugRoute,
  } as any)
const OrgSlugRepositoriesGithubSetupRoute =
  OrgSlugRepositoriesGithubSetupRouteImport.update({
    id: '/repositories/github/setup',
    path: '/repositories/github/setup',
    getParentRoute: () => OrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/.workspace-ui-prototype': typeof DotworkspaceUiPrototypeRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/connectors': typeof OrgSlugConnectorsRoute
  '/$orgSlug/setup': typeof OrgSlugSetupRoute
  '/.amp/events': typeof DotampEventsRoute
  '/.auth/$authView': typeof DotauthAuthViewRoute
  '/.auth/account': typeof DotauthAccountRouteWithChildren
  '/.auth/consent': typeof DotauthConsentRoute
  '/.auth/device': typeof DotauthDeviceRoute
  '/.auth/reset-password': typeof DotauthResetPasswordRoute
  '/.auth/sign-in': typeof DotauthSignInRoute
  '/.github/setup': typeof DotgithubSetupRoute
  '/.notion/setup': typeof DotnotionSetupRoute
  '/.slack/setup': typeof DotslackSetupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
  '/$orgSlug/workspaces/new': typeof OrgSlugWorkspacesNewRoute
  '/$orgSlug/ws/$workspaceSlug': typeof OrgSlugWsWorkspaceSlugRouteWithChildren
  '/.auth/account/$accountView': typeof DotauthAccountAccountViewRoute
  '/.auth/organization/$organizationView': typeof DotauthOrganizationOrganizationViewRoute
  '/$orgSlug/repositories/github/setup': typeof OrgSlugRepositoriesGithubSetupRoute
  '/$orgSlug/ws/$workspaceSlug/$conversationId': typeof OrgSlugWsWorkspaceSlugConversationIdRoute
  '/$orgSlug/ws/$workspaceSlug/': typeof OrgSlugWsWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.workspace-ui-prototype': typeof DotworkspaceUiPrototypeRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/connectors': typeof OrgSlugConnectorsRoute
  '/$orgSlug/setup': typeof OrgSlugSetupRoute
  '/.amp/events': typeof DotampEventsRoute
  '/.auth/$authView': typeof DotauthAuthViewRoute
  '/.auth/account': typeof DotauthAccountRouteWithChildren
  '/.auth/consent': typeof DotauthConsentRoute
  '/.auth/device': typeof DotauthDeviceRoute
  '/.auth/reset-password': typeof DotauthResetPasswordRoute
  '/.auth/sign-in': typeof DotauthSignInRoute
  '/.github/setup': typeof DotgithubSetupRoute
  '/.notion/setup': typeof DotnotionSetupRoute
  '/.slack/setup': typeof DotslackSetupRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
  '/$orgSlug/workspaces/new': typeof OrgSlugWorkspacesNewRoute
  '/.auth/account/$accountView': typeof DotauthAccountAccountViewRoute
  '/.auth/organization/$organizationView': typeof DotauthOrganizationOrganizationViewRoute
  '/$orgSlug/repositories/github/setup': typeof OrgSlugRepositoriesGithubSetupRoute
  '/$orgSlug/ws/$workspaceSlug/$conversationId': typeof OrgSlugWsWorkspaceSlugConversationIdRoute
  '/$orgSlug/ws/$workspaceSlug': typeof OrgSlugWsWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/.workspace-ui-prototype': typeof DotworkspaceUiPrototypeRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/connectors': typeof OrgSlugConnectorsRoute
  '/$orgSlug/setup': typeof OrgSlugSetupRoute
  '/.amp/events': typeof DotampEventsRoute
  '/.auth/$authView': typeof DotauthAuthViewRoute
  '/.auth/account': typeof DotauthAccountRouteWithChildren
  '/.auth/consent': typeof DotauthConsentRoute
  '/.auth/device': typeof DotauthDeviceRoute
  '/.auth/reset-password': typeof DotauthResetPasswordRoute
  '/.auth/sign-in': typeof DotauthSignInRoute
  '/.github/setup': typeof DotgithubSetupRoute
  '/.notion/setup': typeof DotnotionSetupRoute
  '/.slack/setup': typeof DotslackSetupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
  '/$orgSlug/workspaces/new': typeof OrgSlugWorkspacesNewRoute
  '/$orgSlug/ws/$workspaceSlug': typeof OrgSlugWsWorkspaceSlugRouteWithChildren
  '/.auth/account/$accountView': typeof DotauthAccountAccountViewRoute
  '/.auth/organization/$organizationView': typeof DotauthOrganizationOrganizationViewRoute
  '/$orgSlug/repositories/github/setup': typeof OrgSlugRepositoriesGithubSetupRoute
  '/$orgSlug/ws/$workspaceSlug/$conversationId': typeof OrgSlugWsWorkspaceSlugConversationIdRoute
  '/$orgSlug/ws/$workspaceSlug/': typeof OrgSlugWsWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/.workspace-ui-prototype'
    | '/onboarding'
    | '/$orgSlug/connectors'
    | '/$orgSlug/setup'
    | '/.amp/events'
    | '/.auth/$authView'
    | '/.auth/account'
    | '/.auth/consent'
    | '/.auth/device'
    | '/.auth/reset-password'
    | '/.auth/sign-in'
    | '/.github/setup'
    | '/.notion/setup'
    | '/.slack/setup'
    | '/$orgSlug/'
    | '/$orgSlug/organization/$organizationView'
    | '/$orgSlug/workspaces/new'
    | '/$orgSlug/ws/$workspaceSlug'
    | '/.auth/account/$accountView'
    | '/.auth/organization/$organizationView'
    | '/$orgSlug/repositories/github/setup'
    | '/$orgSlug/ws/$workspaceSlug/$conversationId'
    | '/$orgSlug/ws/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.workspace-ui-prototype'
    | '/onboarding'
    | '/$orgSlug/connectors'
    | '/$orgSlug/setup'
    | '/.amp/events'
    | '/.auth/$authView'
    | '/.auth/account'
    | '/.auth/consent'
    | '/.auth/device'
    | '/.auth/reset-password'
    | '/.auth/sign-in'
    | '/.github/setup'
    | '/.notion/setup'
    | '/.slack/setup'
    | '/$orgSlug'
    | '/$orgSlug/organization/$organizationView'
    | '/$orgSlug/workspaces/new'
    | '/.auth/account/$accountView'
    | '/.auth/organization/$organizationView'
    | '/$orgSlug/repositories/github/setup'
    | '/$orgSlug/ws/$workspaceSlug/$conversationId'
    | '/$orgSlug/ws/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/.workspace-ui-prototype'
    | '/onboarding'
    | '/$orgSlug/connectors'
    | '/$orgSlug/setup'
    | '/.amp/events'
    | '/.auth/$authView'
    | '/.auth/account'
    | '/.auth/consent'
    | '/.auth/device'
    | '/.auth/reset-password'
    | '/.auth/sign-in'
    | '/.github/setup'
    | '/.notion/setup'
    | '/.slack/setup'
    | '/$orgSlug/'
    | '/$orgSlug/organization/$organizationView'
    | '/$orgSlug/workspaces/new'
    | '/$orgSlug/ws/$workspaceSlug'
    | '/.auth/account/$accountView'
    | '/.auth/organization/$organizationView'
    | '/$orgSlug/repositories/github/setup'
    | '/$orgSlug/ws/$workspaceSlug/$conversationId'
    | '/$orgSlug/ws/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  DotworkspaceUiPrototypeRoute: typeof DotworkspaceUiPrototypeRoute
  OnboardingRoute: typeof OnboardingRoute
  DotampEventsRoute: typeof DotampEventsRoute
  DotauthAuthViewRoute: typeof DotauthAuthViewRoute
  DotauthAccountRoute: typeof DotauthAccountRouteWithChildren
  DotauthConsentRoute: typeof DotauthConsentRoute
  DotauthDeviceRoute: typeof DotauthDeviceRoute
  DotauthResetPasswordRoute: typeof DotauthResetPasswordRoute
  DotauthSignInRoute: typeof DotauthSignInRoute
  DotgithubSetupRoute: typeof DotgithubSetupRoute
  DotnotionSetupRoute: typeof DotnotionSetupRoute
  DotslackSetupRoute: typeof DotslackSetupRoute
  DotauthOrganizationOrganizationViewRoute: typeof DotauthOrganizationOrganizationViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.workspace-ui-prototype': {
      id: '/.workspace-ui-prototype'
      path: '/.workspace-ui-prototype'
      fullPath: '/.workspace-ui-prototype'
      preLoaderRoute: typeof DotworkspaceUiPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/.slack/setup': {
      id: '/.slack/setup'
      path: '/.slack/setup'
      fullPath: '/.slack/setup'
      preLoaderRoute: typeof DotslackSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.notion/setup': {
      id: '/.notion/setup'
      path: '/.notion/setup'
      fullPath: '/.notion/setup'
      preLoaderRoute: typeof DotnotionSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.github/setup': {
      id: '/.github/setup'
      path: '/.github/setup'
      fullPath: '/.github/setup'
      preLoaderRoute: typeof DotgithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/sign-in': {
      id: '/.auth/sign-in'
      path: '/.auth/sign-in'
      fullPath: '/.auth/sign-in'
      preLoaderRoute: typeof DotauthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/reset-password': {
      id: '/.auth/reset-password'
      path: '/.auth/reset-password'
      fullPath: '/.auth/reset-password'
      preLoaderRoute: typeof DotauthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/device': {
      id: '/.auth/device'
      path: '/.auth/device'
      fullPath: '/.auth/device'
      preLoaderRoute: typeof DotauthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/consent': {
      id: '/.auth/consent'
      path: '/.auth/consent'
      fullPath: '/.auth/consent'
      preLoaderRoute: typeof DotauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/account': {
      id: '/.auth/account'
      path: '/.auth/account'
      fullPath: '/.auth/account'
      preLoaderRoute: typeof DotauthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/$authView': {
      id: '/.auth/$authView'
      path: '/.auth/$authView'
      fullPath: '/.auth/$authView'
      preLoaderRoute: typeof DotauthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.amp/events': {
      id: '/.amp/events'
      path: '/.amp/events'
      fullPath: '/.amp/events'
      preLoaderRoute: typeof DotampEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/setup': {
      id: '/$orgSlug/setup'
      path: '/setup'
      fullPath: '/$orgSlug/setup'
      preLoaderRoute: typeof OrgSlugSetupRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/connectors': {
      id: '/$orgSlug/connectors'
      path: '/connectors'
      fullPath: '/$orgSlug/connectors'
      preLoaderRoute: typeof OrgSlugConnectorsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/.auth/organization/$organizationView': {
      id: '/.auth/organization/$organizationView'
      path: '/.auth/organization/$organizationView'
      fullPath: '/.auth/organization/$organizationView'
      preLoaderRoute: typeof DotauthOrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.auth/account/$accountView': {
      id: '/.auth/account/$accountView'
      path: '/$accountView'
      fullPath: '/.auth/account/$accountView'
      preLoaderRoute: typeof DotauthAccountAccountViewRouteImport
      parentRoute: typeof DotauthAccountRoute
    }
    '/$orgSlug/ws/$workspaceSlug': {
      id: '/$orgSlug/ws/$workspaceSlug'
      path: '/ws/$workspaceSlug'
      fullPath: '/$orgSlug/ws/$workspaceSlug'
      preLoaderRoute: typeof OrgSlugWsWorkspaceSlugRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/workspaces/new': {
      id: '/$orgSlug/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/$orgSlug/workspaces/new'
      preLoaderRoute: typeof OrgSlugWorkspacesNewRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/organization/$organizationView': {
      id: '/$orgSlug/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/$orgSlug/organization/$organizationView'
      preLoaderRoute: typeof OrgSlugOrganizationOrganizationViewRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/ws/$workspaceSlug/': {
      id: '/$orgSlug/ws/$workspaceSlug/'
      path: '/'
      fullPath: '/$orgSlug/ws/$workspaceSlug/'
      preLoaderRoute: typeof OrgSlugWsWorkspaceSlugIndexRouteImport
      parentRoute: typeof OrgSlugWsWorkspaceSlugRoute
    }
    '/$orgSlug/ws/$workspaceSlug/$conversationId': {
      id: '/$orgSlug/ws/$workspaceSlug/$conversationId'
      path: '/$conversationId'
      fullPath: '/$orgSlug/ws/$workspaceSlug/$conversationId'
      preLoaderRoute: typeof OrgSlugWsWorkspaceSlugConversationIdRouteImport
      parentRoute: typeof OrgSlugWsWorkspaceSlugRoute
    }
    '/$orgSlug/repositories/github/setup': {
      id: '/$orgSlug/repositories/github/setup'
      path: '/repositories/github/setup'
      fullPath: '/$orgSlug/repositories/github/setup'
      preLoaderRoute: typeof OrgSlugRepositoriesGithubSetupRouteImport
      parentRoute: typeof OrgSlugRoute
    }
  }
}

interface OrgSlugWsWorkspaceSlugRouteChildren {
  OrgSlugWsWorkspaceSlugConversationIdRoute: typeof OrgSlugWsWorkspaceSlugConversationIdRoute
  OrgSlugWsWorkspaceSlugIndexRoute: typeof OrgSlugWsWorkspaceSlugIndexRoute
}

const OrgSlugWsWorkspaceSlugRouteChildren: OrgSlugWsWorkspaceSlugRouteChildren =
  {
    OrgSlugWsWorkspaceSlugConversationIdRoute:
      OrgSlugWsWorkspaceSlugConversationIdRoute,
    OrgSlugWsWorkspaceSlugIndexRoute: OrgSlugWsWorkspaceSlugIndexRoute,
  }

const OrgSlugWsWorkspaceSlugRouteWithChildren =
  OrgSlugWsWorkspaceSlugRoute._addFileChildren(
    OrgSlugWsWorkspaceSlugRouteChildren,
  )

interface OrgSlugRouteChildren {
  OrgSlugConnectorsRoute: typeof OrgSlugConnectorsRoute
  OrgSlugSetupRoute: typeof OrgSlugSetupRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugOrganizationOrganizationViewRoute: typeof OrgSlugOrganizationOrganizationViewRoute
  OrgSlugWorkspacesNewRoute: typeof OrgSlugWorkspacesNewRoute
  OrgSlugWsWorkspaceSlugRoute: typeof OrgSlugWsWorkspaceSlugRouteWithChildren
  OrgSlugRepositoriesGithubSetupRoute: typeof OrgSlugRepositoriesGithubSetupRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugConnectorsRoute: OrgSlugConnectorsRoute,
  OrgSlugSetupRoute: OrgSlugSetupRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugOrganizationOrganizationViewRoute:
    OrgSlugOrganizationOrganizationViewRoute,
  OrgSlugWorkspacesNewRoute: OrgSlugWorkspacesNewRoute,
  OrgSlugWsWorkspaceSlugRoute: OrgSlugWsWorkspaceSlugRouteWithChildren,
  OrgSlugRepositoriesGithubSetupRoute: OrgSlugRepositoriesGithubSetupRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface DotauthAccountRouteChildren {
  DotauthAccountAccountViewRoute: typeof DotauthAccountAccountViewRoute
}

const DotauthAccountRouteChildren: DotauthAccountRouteChildren = {
  DotauthAccountAccountViewRoute: DotauthAccountAccountViewRoute,
}

const DotauthAccountRouteWithChildren = DotauthAccountRoute._addFileChildren(
  DotauthAccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  DotworkspaceUiPrototypeRoute: DotworkspaceUiPrototypeRoute,
  OnboardingRoute: OnboardingRoute,
  DotampEventsRoute: DotampEventsRoute,
  DotauthAuthViewRoute: DotauthAuthViewRoute,
  DotauthAccountRoute: DotauthAccountRouteWithChildren,
  DotauthConsentRoute: DotauthConsentRoute,
  DotauthDeviceRoute: DotauthDeviceRoute,
  DotauthResetPasswordRoute: DotauthResetPasswordRoute,
  DotauthSignInRoute: DotauthSignInRoute,
  DotgithubSetupRoute: DotgithubSetupRoute,
  DotnotionSetupRoute: DotnotionSetupRoute,
  DotslackSetupRoute: DotslackSetupRoute,
  DotauthOrganizationOrganizationViewRoute:
    DotauthOrganizationOrganizationViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
