/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as OrgSlugSignInRouteImport } from './routes/$orgSlug.sign-in'
import { Route as OrgSlugResetPasswordRouteImport } from './routes/$orgSlug.reset-password'
import { Route as OrgSlugAccountRouteImport } from './routes/$orgSlug.account'
import { Route as OrgSlugOrganizationOrganizationViewRouteImport } from './routes/$orgSlug.organization.$organizationView'
import { Route as OrgSlugAuthAuthViewRouteImport } from './routes/$orgSlug.auth.$authView'
import { Route as OrgSlugAccountAccountViewRouteImport } from './routes/$orgSlug.account.$accountView'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSignInRoute = OrgSlugSignInRouteImport.update({
  id: '/$orgSlug/sign-in',
  path: '/$orgSlug/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugResetPasswordRoute = OrgSlugResetPasswordRouteImport.update({
  id: '/$orgSlug/reset-password',
  path: '/$orgSlug/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAccountRoute = OrgSlugAccountRouteImport.update({
  id: '/$orgSlug/account',
  path: '/$orgSlug/account',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugOrganizationOrganizationViewRoute =
  OrgSlugOrganizationOrganizationViewRouteImport.update({
    id: '/$orgSlug/organization/$organizationView',
    path: '/$orgSlug/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAuthAuthViewRoute = OrgSlugAuthAuthViewRouteImport.update({
  id: '/$orgSlug/auth/$authView',
  path: '/$orgSlug/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAccountAccountViewRoute =
  OrgSlugAccountAccountViewRouteImport.update({
    id: '/$accountView',
    path: '/$accountView',
    getParentRoute: () => OrgSlugAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug/account': typeof OrgSlugAccountRouteWithChildren
  '/$orgSlug/reset-password': typeof OrgSlugResetPasswordRoute
  '/$orgSlug/sign-in': typeof OrgSlugSignInRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/account/$accountView': typeof OrgSlugAccountAccountViewRoute
  '/$orgSlug/auth/$authView': typeof OrgSlugAuthAuthViewRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug/account': typeof OrgSlugAccountRouteWithChildren
  '/$orgSlug/reset-password': typeof OrgSlugResetPasswordRoute
  '/$orgSlug/sign-in': typeof OrgSlugSignInRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/account/$accountView': typeof OrgSlugAccountAccountViewRoute
  '/$orgSlug/auth/$authView': typeof OrgSlugAuthAuthViewRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug/account': typeof OrgSlugAccountRouteWithChildren
  '/$orgSlug/reset-password': typeof OrgSlugResetPasswordRoute
  '/$orgSlug/sign-in': typeof OrgSlugSignInRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/account/$accountView': typeof OrgSlugAccountAccountViewRoute
  '/$orgSlug/auth/$authView': typeof OrgSlugAuthAuthViewRoute
  '/$orgSlug/organization/$organizationView': typeof OrgSlugOrganizationOrganizationViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug/account'
    | '/$orgSlug/reset-password'
    | '/$orgSlug/sign-in'
    | '/$orgSlug/'
    | '/$orgSlug/account/$accountView'
    | '/$orgSlug/auth/$authView'
    | '/$orgSlug/organization/$organizationView'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug/account'
    | '/$orgSlug/reset-password'
    | '/$orgSlug/sign-in'
    | '/$orgSlug'
    | '/$orgSlug/account/$accountView'
    | '/$orgSlug/auth/$authView'
    | '/$orgSlug/organization/$organizationView'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug/account'
    | '/$orgSlug/reset-password'
    | '/$orgSlug/sign-in'
    | '/$orgSlug/'
    | '/$orgSlug/account/$accountView'
    | '/$orgSlug/auth/$authView'
    | '/$orgSlug/organization/$organizationView'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugAccountRoute: typeof OrgSlugAccountRouteWithChildren
  OrgSlugResetPasswordRoute: typeof OrgSlugResetPasswordRoute
  OrgSlugSignInRoute: typeof OrgSlugSignInRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugAuthAuthViewRoute: typeof OrgSlugAuthAuthViewRoute
  OrgSlugOrganizationOrganizationViewRoute: typeof OrgSlugOrganizationOrganizationViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/sign-in': {
      id: '/$orgSlug/sign-in'
      path: '/$orgSlug/sign-in'
      fullPath: '/$orgSlug/sign-in'
      preLoaderRoute: typeof OrgSlugSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/reset-password': {
      id: '/$orgSlug/reset-password'
      path: '/$orgSlug/reset-password'
      fullPath: '/$orgSlug/reset-password'
      preLoaderRoute: typeof OrgSlugResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/account': {
      id: '/$orgSlug/account'
      path: '/$orgSlug/account'
      fullPath: '/$orgSlug/account'
      preLoaderRoute: typeof OrgSlugAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/organization/$organizationView': {
      id: '/$orgSlug/organization/$organizationView'
      path: '/$orgSlug/organization/$organizationView'
      fullPath: '/$orgSlug/organization/$organizationView'
      preLoaderRoute: typeof OrgSlugOrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/auth/$authView': {
      id: '/$orgSlug/auth/$authView'
      path: '/$orgSlug/auth/$authView'
      fullPath: '/$orgSlug/auth/$authView'
      preLoaderRoute: typeof OrgSlugAuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/account/$accountView': {
      id: '/$orgSlug/account/$accountView'
      path: '/$accountView'
      fullPath: '/$orgSlug/account/$accountView'
      preLoaderRoute: typeof OrgSlugAccountAccountViewRouteImport
      parentRoute: typeof OrgSlugAccountRoute
    }
  }
}

interface OrgSlugAccountRouteChildren {
  OrgSlugAccountAccountViewRoute: typeof OrgSlugAccountAccountViewRoute
}

const OrgSlugAccountRouteChildren: OrgSlugAccountRouteChildren = {
  OrgSlugAccountAccountViewRoute: OrgSlugAccountAccountViewRoute,
}

const OrgSlugAccountRouteWithChildren = OrgSlugAccountRoute._addFileChildren(
  OrgSlugAccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugAccountRoute: OrgSlugAccountRouteWithChildren,
  OrgSlugResetPasswordRoute: OrgSlugResetPasswordRoute,
  OrgSlugSignInRoute: OrgSlugSignInRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugAuthAuthViewRoute: OrgSlugAuthAuthViewRoute,
  OrgSlugOrganizationOrganizationViewRoute:
    OrgSlugOrganizationOrganizationViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
