packages:
  - apps/*
  - packages/*
  - examples/*

patchedDependencies:
  '@asteasolutions/zod-to-openapi@8.4.1': patches/@asteasolutions__zod-to-openapi@8.4.1.patch
  '@cosmograph/cosmograph@2.2.1': patches/@cosmograph__cosmograph@2.2.1.patch
  '@hono/zod-openapi@1.2.2': patches/@hono__zod-openapi@1.2.2.patch
  '@langchain/langgraph-api@1.1.13': patches/@langchain__langgraph-api@1.1.13.patch
