// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ProjectDefaultEnvironment {
    /**
     * Identifier of the default environment.
     */
    id?: pulumi.Input<string>;
    /**
     * Name of the default environment.
     */
    name?: pulumi.Input<string>;
}

export interface ServiceRegion {
    /**
     * Number of replicas to deploy. **Default** <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`">`1`</span>.
     */
    numReplicas?: pulumi.Input<number>;
    /**
     * Region to deploy in.
     */
    region?: pulumi.Input<string>;
}

export interface ServiceVolume {
    /**
     * Identifier of the volume.
     */
    id?: pulumi.Input<string>;
    /**
     * Mount path of the volume.
     */
    mountPath: pulumi.Input<string>;
    /**
     * Name of the volume.
     */
    name: pulumi.Input<string>;
    /**
     * Size of the volume in MB.
     */
    size?: pulumi.Input<number>;
}

export interface VariableCollectionVariable {
    /**
     * Name of the variable.
     */
    name: pulumi.Input<string>;
    /**
     * Value of the variable.
     */
    value: pulumi.Input<string>;
}
